### ISSUE TITLE
Fetching certain HTTPS requests fails with "unexpected end of file"

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#13058]
```js
const res = await fetch("https://wpt.live/resources/testharness.js");
await res.text();
```

```
Uncaught Error: request or response body error: error reading a body from connection: unexpected end of file
    at async Object.pull (deno:ext/fetch/26_fetch.js:108:24)
```

This doesn't fail with every HTTPS request – https://wpt.live/resources/ works, for example – but it seems to be consistent when it does. It doesn't happen with HTTP at all.

This seems to have been introduced in the upgrade to rustls 0.20 in #12488.

**Comment by andreubotella** [comment]
This is an upstream bug: rustls/hyper-rustls#162

**Comment by lucacasonato** [comment]
We may need to revert the rustls 0.20 update until we figure this out. The nature of the issue could result in problems outside of WPT.

**Comment by bradenmacdonald** [comment]
What I assume is the same issue is also causing Deno to fail to cache deps or run type checks on GitHub Actions CI, which has broken my app's builds. For some reason it doesn't seem to happen on my local MacOS Deno, even though it's the same version.

```
Run deno run ... --unstable --no-check scripts/test-setup.ts
...
Download...
error: error sending request for url (https://deno.land/x/god_crypto@v1.4.9/src/utility/asn1.ts): connection error: unexpected end of file
    at https://deno.land/x/god_crypto@v1.4.9/src/rsa/export_key.ts:4:21
Error: Process completed with exit code 1.
```

and 

```
Run deno cache --import-map=import_map.json --unstable scripts/test-setup.ts
Download...
error: error sending request for url (https://deno.land/std@0.113.0/streams/conversion.ts): error trying to connect: tls handshake eof
    at file:///home/runner/work/.../core/objstore/objstore.ts:4:42
Error: Process completed with exit code 1.
```

I have re-run the tests several times and fail similarly each time, though often on a different file.

This is Deno 1.17.0 running on GitHub Actions default ubuntu runner.

**Comment by joao10lima** [comment]
> What I assume is the same issue is also causing Deno to fail to cache deps or run type checks on GitHub Actions CI, which has broken my app's builds. For some reason it doesn't seem to happen on my local MacOS Deno, even though it's the same version.
> 
> ```
> Run deno run ... --unstable --no-check scripts/test-setup.ts
> ...
> Download...
> error: error sending request for url (https://deno.land/x/god_crypto@v1.4.9/src/utility/asn1.ts): connection error: unexpected end of file
>     at https://deno.land/x/god_crypto@v1.4.9/src/rsa/export_key.ts:4:21
> Error: Process completed with exit code 1.
> ```
> 
> and
> 
> ```
> Run deno cache --import-map=import_map.json --unstable scripts/test-setup.ts
> Download...
> error: error sending request for url (https://deno.land/std@0.113.0/streams/conversion.ts): error trying to connect: tls handshake eof
>     at file:///home/runner/work/.../core/objstore/objstore.ts:4:42
> Error: Process completed with exit code 1.
> ```
> 
> I have re-run the tests several times and they fail similarly each time, though often on a different file.
> 
> This is Deno 1.17.0 running on GitHub Actions default ubuntu runner.

Same here
https://github.com/pipelinit/pipelinit-cli/runs/5235744784?check_suite_focus=true

**Comment by c4p-n1ck** [comment]
No fix? not even some monkey-patch?

Like what do I do now? Re-write the entire project in another language? :confused:

**Comment by Lonniebiz** [comment]
Seriously, other than node.js, does anyone have a work-around?

**Comment by djc** [comment]
I think one reason this hasn't gotten "fixed" is that it's arguably a bug on the server side. rustls in 0.20 has become more strict about reporting an error if the peer closes its connection without sending a CloseNotify alert, but as I read RFC 5246 and RFC 8446 they do require sending the alert before closing the (write side of) the connection. So it might be interesting to report servers you're seeing this with and figuring out which TLS stack is running on those servers.

**Comment by lucacasonato** [comment]
@djc It fails when Deno connects to another Deno server, so rustls on both client and server.

**Comment by lucacasonato** [comment]
The other server it is known to fail on is the web-platform-test server which uses Python’s built in TLS, which uses OpenSSL.

**Comment by djc** [comment]
Well, I feel like there might something specific about Deno because I have not heard from anyone else that's run into similar issues, even though rustls 0.20 has seen significant uptake since it's release 9 months ago.

**Comment by lucacasonato** [comment]
@djc That's good info to have. I'll see if I can find anything specific. For client side HTTP, we use `reqwest`, which uses `hyper-rustls` under the hood. For server side TLS we use our own rustls<->hyper binding code.

I'll see if I can reproduce the failures when making requests to the WPT test server by just using `reqwest`.

**Comment by djc** [comment]
It would be good to check if there are similar issues in the reqwest issue tracker. Also good to focus on the error handling edge cases in the integration between Deno and reqwest on the client side and also (perhaps particularly) on the server side.

**Comment by Lonniebiz** [comment]
Guys, I'm looking for practical solutions that I can implement until this is fixed.

For example, I running deno verison 1.22.2 on this project. Does anyone know which version of Deno precedes this bug? Perhaps I can downgrade to a version of deno where this bug goes away, and later upgrade to the latest deno once it is confirmed fix.

It is my understanding that the reason Deno is throwing this error, is because the web server I'm requesting from isn't always "sending a CloseNotify alert before closing their response stream".

I tire very quickly of frameworks that prioritize correctness over robustness. Something that's not correct is only worthy of a **warning** if that correctness can be ignored to achieve robustness.

**Comment by Lonniebiz** [comment]
As workaround, I thinking about just retrying the fetch when the bug occurs. Something like this:
https://dev.to/ycmjason/javascript-fetch-retry-upon-failure-3p6g

For me, the bug rarely happens twice in a row, so maybe I can get past it buy just retrying x number of times.

**Comment by karagraysen** [comment]
@TimDev9492 Did you find a solution?
@Lonniebiz Is there any movement on this issue or any way I can assist? Thanks!

**Comment by bombillazo** [comment]
Any solution to this when running `deno compile`? our deploys are failing due to the deno dependency downloads failing during the compile process.

**Comment by RafalKornel** [comment]
Any progress on this issue?

In my small script I am performing some amount of fetches (ex. few thousands)
When I try using `await Promise.all(...)`, then I get +- this result:
<img width="534" alt="image" src="https://github.com/denoland/deno/assets/38111105/cffd3b0c-b721-407b-abca-70a377c269ac">

However, when I change script's logic and try to iterate over promises and await each of them, then all fetches are successfull.
<img width="537" alt="image" src="https://github.com/denoland/deno/assets/38111105/f24a6c50-720b-46cb-9c7a-e6cb930be429">

<img width="498" alt="image" src="https://github.com/denoland/deno/assets/38111105/787cc570-7145-4f73-9ada-6589a948efef">

**Comment by dgreensp** [comment]
I seem to be getting this error in a Deno Deploy GitHub Action when it's fetching from esm.sh, and it's holding up my CI.  Bizarre.  I have no idea how to fix this if the problem is buggy HTTPS code at some relatively low level of the stack inside Deno or esm.sh. :(

EDIT: Never mind, it seems either esm.sh was having a temporary issue, or it was fixed by upgrading my local Deno, recreating the lockfile, and stuff like that.

**Comment by bartlomieju** [comment]
Still reproducible on Deno 2.8.1. Confirmed root cause:

```js
const res = await fetch("https://wpt.live/resources/testharness.js");
await res.text();
// TypeError: error reading a body from connection
```

`curl` fetches the same URL completely (200, 198291 bytes), Deno fails.

The response from that endpoint is **close-delimited** — the GET response carries no `Content-Length` and no `Transfer-Encoding` (it is served by Python `BaseHTTP`), so the end of the body is signaled only by the connection closing. When such a server closes the TLS connection **without sending a `close_notify` alert**, rustls returns `UnexpectedEof`, and hyper/Deno cannot distinguish a clean end of an EOF-delimited body from a truncated stream, so it surfaces "error reading a body from connection".

This matches the original diagnosis (regressed in the rustls 0.20 upgrade, #12488). It is intermittent across servers because it only triggers when a server both omits `close_notify` and uses EOF framing. curl and browsers deliberately tolerate a missing `close_notify` for close-delimited bodies.

rustls exposes a way to tolerate an unclean close, so the fix is actionable in Deno: treat `UnexpectedEof` as a clean end for EOF-delimited response bodies, matching curl/browser behavior.
