### ISSUE TITLE
Random segmentation fault errors

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#20072]
For a long time I'm getting random errors running Lightningcss plugin on Lume:

```
[1]    81218 done                echo "import 'lume/cli.ts'" | 
       81219 segmentation fault  deno run --unstable -A - "-s"
```

The Lightningcss library is run via napi and for some weird reason, Deno panick when I add some specific `@import` rules in my CSS file.

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.36.0
Args: ["deno", "run", "--unstable", "-A", "-", "-s"]

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', cli/napi/threadsafe_functions.rs:126:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Sorry, I cannot be more specific because it doesn't always happen, so I wasn't able to reproduce this error consistently. I think it didn't happen with the wasm version of Lightningcss, so I suspect it's something related with napi.

**Comment by bartlomieju** [comment]
Thanks for the report @oscarotero, I do believe this is actually caused by N-API integration. We'll try to look into fixing this. Any chance you could provide a boiled down reproduction?

**Comment by oscarotero** [comment]
After removing the Deno's cache folder, the segmentation fault error has gone but the Deno panick error is still there.

To reproduce it, [clone the following repo](https://github.com/lumeland/lume.land/tree/lightningcss), go to `lighningcss` branch and run `deno task build`.

The panick error is related with the following line https://github.com/lumeland/lume.land/blob/lightningcss/_includes/styles/reset.css#L1. After removing it, it works fine.

**Comment by oscarotero** [comment]
I don't know if this is related, but on running the tests, sometimes the `lightningcss` plugin tests stops the testing and shows this message:

```
lightningcss plugin (only transform) ... ok (87ms)
lightningcss plugin (bundle mode) ... ok (18ms)
deno(52814,0x70000ed31000) malloc: *** error for object 0x7f79b39a9848: pointer being freed was not allocated
deno(52814,0x70000ed31000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by bartlomieju** [comment]
@oscarotero I believe this is purely a race condition in our implementation of "thread safe functions" for Node-API. We wanted to rewrite them for some time now. We'll try to look into the problem next week.

**Comment by oscarotero** [comment]
Great, thanks!

**Comment by bartlomieju** [comment]
@oscarotero we found the culprit and should fix it shortly, however with your reproduction we are always getting `error: Uncaught (in promise) Error`. Is that expected?

**Comment by oscarotero** [comment]
@bartlomieju Great!
I just test it after upgrading deno to the canary version and I can confirm it works fine. The returning error is a bug on my side, sorry.

Thank you!

**Comment by bartlomieju** [comment]
@oscarotero that's strange, since the PR in question is https://github.com/denoland/deno/pull/20324 and it hasn't landed yet. Anyway, I'll land it in the coming days. Let me know if you encounter any more problems.

**Comment by oscarotero** [comment]
Okay, the panick error still happens randomly (even on canary).
But after fixing the bug in Lume, it's gone.

**Comment by oscarotero** [comment]
Hi again.
Thanks for fixing the panick issue!
Unfortunately, I continue getting random segmentation faults running lightningcss. 

<img width="907" alt="imaxe" src="https://github.com/denoland/deno/assets/377873/b546c246-f712-4e23-b7fd-ce6b5a016e3c">

It happens randomly, once every 3-4 builds. I don't know if it's an issue from Deno or Lightningcss (It doesn't happen with postcss). I've created this branch https://github.com/lumeland/lume.land/tree/lightningcss if you want to take a look.

**Comment by oscarotero** [comment]
Hi again.
Just want to share another example of random error with lightningcss that just happened in the tests: https://github.com/lumeland/lume/actions/runs/6077032533/job/16486035341#step:6:1317

**Comment by oscarotero** [comment]
Another error. This time it's different: https://github.com/lumeland/lume/actions/runs/6078386604/job/16489483050#step:6:1326

**Comment by tsaxking** [comment]
I'm having a similar problem with `npm:express`, if I add a single middleware function, it gives me the error: `/snap/deno/118/wrapper.sh: line 15: 14346 Segmentation fault      $SNAP/deno "${@}"` then exits the process. It's always the same middleware function, but it still throws that error if all it does is `next();`.

**Comment by devsnek** [comment]
napi_threadsafe_function was rewritten in https://github.com/denoland/deno/pull/24101 and shouldn't hit this case anymore. Let us know if you run into additional issues.
