### ISSUE TITLE
Node compatibility issue with handling multipart/form-data files

### ISSUE THREAD

**Issue by firecakes** [denoland/deno#20284]
I've been noticing file corruption issues while letting the `koa-body` library handle multiple files with `multipart/form-data` requests. In the Deno server code where I'm using the npm modules some files get corrupted during the save while with NodeJS the files are saved fine. I'm using Deno v1.36.3, and the issue can reliably happen as long as you're selecting 20+ images on the browser as a multi-file upload to the server.

Client code that sends the request:

```js
const formData = new FormData();
for (let i = 0; i < event.target.files.length; i++) {
  const file = event.target.files[i];
  formData.append('myFile', file);
}

const results = await axios.post('/api/file', formData, {
  headers: {
    'Content-Type': 'multipart/form-data'
  }
});
```

Server code in Deno:

```js
import Koa from "npm:koa@2.14.2";
import Router from "npm:@koa/router@12.0.0";
import serve from "npm:koa-static@5.0.0";
import { koaBody } from "npm:koa-body@6.0.1";
import { createReadStream } from "node:fs";
import http from "node:http";


// start the web server initialization
const app = new Koa();
const router = new Router();

app.use(koaBody({
  parsedMethods: ["POST", "PUT", "PATCH", "DELETE"], // add DELETE as parsed method
  multipart: true, // parse multipart form data
  formidable: { // modify where the form data gets saved
    uploadDir: "static/tmp",
    keepExtensions: true,
    maxFileSize: 10 * 1024 * 1024 * 1024,
  },
}));

// add a new file
router.post("/api/file", async (ctx, next) => {
  if (!Array.isArray(ctx.request.files.myFile)) {
    ctx.request.files.myFile = [ctx.request.files.myFile];
  }

  // rename the files to what they were originally and move them to the correct location
  for await (let file of ctx.request.files.myFile) {
    await Deno.rename(
      `static/tmp/${file.newFilename}`,
      `static/files/${file.originalFilename}`,
    );
  }


  ctx.body = {
    files: ctx.request.files.myFile.map((file) =>
      `files/${file.originalFilename}`
    ),
  };
});

// get files under static folder, and resolve "/" to index.html
app.use(serve("static"));

app.use(router.routes());
app.use(router.allowedMethods());

http.createServer(app.callback()).listen(8000);
```

Server code in NodeJS

```js
import Koa from "koa";
import Router from "@koa/router";
import serve from "koa-static";
import { koaBody } from "koa-body";
import { createReadStream } from "fs";
import http from "http";
import { readdir, rename } from 'node:fs/promises';

// start the web server initialization
const app = new Koa();
const router = new Router();

app.use(koaBody({
  parsedMethods: ["POST", "PUT", "PATCH", "DELETE"], // add DELETE as parsed method
  multipart: true, // parse multipart form data
  formidable: { // modify where the form data gets saved
    uploadDir: "static/tmp",
    keepExtensions: true,
    maxFileSize: 10 * 1024 * 1024 * 1024,
  },
}));

// add a new file
router.post("/api/file", async (ctx, next) => {
  if (!Array.isArray(ctx.request.files.myFile)) {
    ctx.request.files.myFile = [ctx.request.files.myFile];
  }

  // rename the files to what they were originally and move them to the correct location
  for await (let file of ctx.request.files.myFile) {
    await rename(
      `static/tmp/${file.newFilename}`,
      `static/files/${file.originalFilename}`,
    );
  }


  ctx.body = {
    files: ctx.request.files.myFile.map((file) =>
      `files/${file.originalFilename}`
    ),
  };
});

// get files under static folder, and resolve "/" to index.html
app.use(serve("static"));

app.use(router.routes());
app.use(router.allowedMethods());

http.createServer(app.callback()).listen(8000);

```

**Comment by CoenraadS** [comment]
I tried to make this a self contained example to reproduce this, but was unsuccessful:

[repro.zip](https://github.com/denoland/deno/files/12480275/repro.zip)

```
# Launch a server at localhost:8000
```deno run --allow-all server.ts```

# Option 1: Via Web Browser
http://localhost:8000/index.html

Select all the files in the `data` folder, and submit them
```

I added hash printing, and all hashes indicate file was received correctly.

**Comment by firecakes** [comment]
I can be more specific. I was testing uploading PNG files and then trying to read them back in the browser, and this is how I was noticing the data corruption issues, where the data in some of the files gets jumbled up and is unrecognizable as an image file.

The chance of each file being corrupted also appears to be correlated to its file size. For example, a bunch (15+) of images at 305B each had no corruptions. A bunch of 3.5KB images had only one corruption, and a bunch of large 2.1MB images had every image except for one corrupted.

**Comment by CoenraadS** [comment]
Updating file size to 5MB did the trick

Reproduction:

Just run ```deno run --allow-all server.ts```, and it will log hash mismatches

[repro.zip](https://github.com/denoland/deno/files/12482769/repro.zip)

**Comment by bartlomieju** [comment]
Thanks for the report folks. We fixed a big bug in `Socket` class in v1.36.4, is it still reproducible in the latest version?

**Comment by CoenraadS** [comment]
@bartlomieju  Yes, also occurs with `deno 1.36.4 (release, x86_64-pc-windows-msvc)`

**Comment by bartlomieju** [comment]
Thanks, we'll look into that!

**Comment by firecakes** [comment]
Any updates on this @bartlomieju? Also tried this with v1.37.2.

**Comment by CoenraadS** [comment]
I believe this has been fixed in [1.38.3](https://github.com/denoland/deno/releases/tag/v1.38.3)

Thanks to: https://github.com/denoland/deno/pull/21297

**Comment by firecakes** [comment]
Update: I haven't had issues with this since running newer versions of Deno (v1.38.3+). Seems like it got resolved, just wanted to make sure it was intentional before closing the issue.

**Comment by CoenraadS** [comment]
I tested my repro from https://github.com/denoland/deno/issues/20284#issuecomment-1700418050 with 1.40.2 and it still occurs.

**Comment by kt3k** [comment]
@CoenraadS I couldn't reproduce the data corruption using the repro.zip (main.js) with the latest Deno on Windows Server 2022 and MacOS 13.3. Can you still reproduce the error with the latest Deno?

<img width="828" alt="Screenshot 2024-03-27 at 22 36 48" src="https://github.com/denoland/deno/assets/613956/9c093496-9be0-4c0c-a1f0-b71c4ef48a61">

**Comment by dy-dx** [comment]
A [createWriteStream issue](https://github.com/nodejs/node/issues/51993) has just been fixed in node.js, but it still exists in deno.
It might be related to this issue.

Repro:
```js
import fs from 'node:fs';
import process from 'node:process';

const w = fs.createWriteStream('file.txt');

w.on('open', () => {
  w.write('hello');

  process.nextTick(() => {
    w.write('world');
    w.end();
  });
});

w.on('close', () => {
  console.log(fs.readFileSync('file.txt', 'utf8'));
});
```

deno v1.42.0:
```
$ deno run --allow-all index.mjs

worldhello
```

**Comment by CoenraadS** [comment]
@kt3k 

It still occurs for me, sending 2 files I think isn't enough, try bumping it up to a higher number. Usually within the first 10 I get a hash error.

![image](https://github.com/denoland/deno/assets/5593825/9a5723ee-3a4d-4c64-a98d-aafa4856254c)

**Comment by kt3k** [comment]
@CoenraadS Thanks. Now I'm able to reproduce the issue consistently with ~20 iterative checks on macOS.

The issue (with fs.writev excluded) seems to have started from Deno 1.39.3. It doesn't happen with 1.39.2 or lower.

I'll check it in more details soon

**Comment by kt3k** [comment]
@dy-dx Thanks for the input! Looks related to this issue. I tried the patch https://github.com/nodejs/node/pull/52005 together with https://github.com/nodejs/node/pull/46818, but it didn't fix the given example (it still shows `worldhello`).. Do you think of any possible cause of it?
