### ISSUE TITLE
bug: `GPUCanvasContext.configure()` crash with when `alphaMode` or `usage` is set

### ISSUE THREAD

**Issue by FuriouZz** [denoland/deno#22446]
Version: Deno 1.40.5

With the recent annoucement of [BYOW](https://deno.com/blog/v1.40#webgpu-windowing--bring-your-own-window), I created an [project](https://github.com/FuriouZz/deno_webgpu_canvas) to run a [three.js](https://threejs.org/) application with [deno_sdl2](https://github.com/littledivy/deno_sdl2).

I noticed that `GPUCanvasContext.configure()` is quite different that the one described on [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/GPUCanvasContext/configure).

## `width` and `height`

`width` and `height` properties are required

## `alphaMode`

`alphaMode` accepts `"opaque"` and `"premultiplied"` but only `"opaque"` works. 

An error occured when `"premultiplied"` is set: 

```bash
TypeError: unknown variant 'premultiplied', expected one of 'auto', 'opaque', 'preMultiplied', 'postMultiplied', 'inherit'
```

And I got another error if I set `"preMultiplied"`:

```bash
TypeError: [object Object]: The provided value 'preMultiplied' is not a valid enum value of type GPUCanvasAlphaMode.
```

I checked [wgpu-types](https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-types/src/lib.rs#L5149) and `"preMultiplied"` is expected. 

Maybe a map from `"premultiplied"` to `"preMultiplied"` is required?

## `usage`

`usage` crash when different than `GPUTextureUsage.RENDER_ATTACHMENT` (threejs use [`GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_SRC`](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/renderers/webgpu/WebGPUBackend.js#L117)): 

```bash
Error: Surface is not configured for presentation
```

**Comment by littledivy** [comment]
The `premultipled` casing is fixed upstream. https://github.com/gfx-rs/wgpu/pull/4940.

**Comment by Jamesernator** [comment]
> ```shell
> Error: Surface is not configured for presentation
> ```

I'm getting this error also, though it doesn't seem to be related to `usage`. Rather if I use the default adapter (i.e. intel integrated) then this error happens but using the high-performance (nividia) adapter works fine.

**Comment by lucacasonato** [comment]
This should now be fixed.

**Comment by okoibraun** [comment]
Did you try using the "preMultiplied" as is, instead of "preMultiplied"?

**Comment by lucacasonato** [comment]
Oh, actually nope this is still broken. The correct value is `preMultiplied`. This should be fixed by just updating wgpu (cc @crowlKats). Sorry for the noise.
