### ISSUE TITLE
deno compile does not work (2.2.11)

### ISSUE THREAD

**Issue by gowoonhae** [denoland/deno#28982]
Version: Deno 2.2.11

Hello. This comment was written with google translate.

I was studying about a web server that serves static resources with Deno.serve() and executes API functions with file-based routing.

The environment is windows. In deno run, I changed only the command to deno compile and created an .exe file, but it compiles but does not run.

When I lowered the version to 2.2.10, it ran well. I used deno-x86_64-pc-windows-msvc.zip.

deno run --allow-all main.ts
>> possible

deno compile --allow-all main.ts
>> automatically downloads the light version, compiles, but does not run

**Comment by 4013950** [comment]
Same issue after upgrading, downgraded to previous version with `deno upgrade --version 2.2.10` and it works.

**Comment by marvinhagemeister** [comment]
How can we reproduce this issue?

**Comment by gowoonhae** [comment]
![Image](https://github.com/user-attachments/assets/f1c8631c-4fb2-46bf-ae8c-c2946e28d5eb)


In deno 2.2.10, if you run the compiled executable, it works normally.


![Image](https://github.com/user-attachments/assets/9978465f-a421-49eb-9663-1cfd53c919d1)


In deno 2.2.11, running the executable terminates immediately.

**Comment by tiredIsa** [comment]
The same problem, after updating to 2.2.11, the compiled EXEs output nothing. Compilation completes without errors.

**Comment by jbabco** [comment]
Wondering if this is the same issue I'm seeing with 2.2.11 on windows reported [here](https://old.reddit.com/r/Deno/comments/1k3pgep/compile_app_doesnt_output_anything/).

Basically, if compiling on windows, exe doesn't function. Targeting windows exe in linux does work. I never <2.2.11.

**Comment by bartlomieju** [comment]
We're investigating the issue. Does the problem occur on Deno v2.3.0-rc.0 for you? You can try it out by running `deno upgrade rc`.

**Comment by xsamueljr** [comment]
@jbabco 

> Targeting windows exe in linux does work

It's not working for me. I think I can't share the code, but basically compiling the same project with minimal changes after updating from 2.2.10 to 2.2.11 gave me the exact same issue, and I'm compiling for Windows from Linux

**Comment by tiredIsa** [comment]
> We're investigating the issue. Does the problem occur on Deno v2.3.0-rc.0 for you? You can try it out by running `deno upgrade rc`.

For me on Windows, it doesn't work. It's the same problem as with 2.2.11.

![Image](https://github.com/user-attachments/assets/660fc713-85eb-4d4c-abdb-d9ad3cbe8df4)

**Comment by realChakrawarti** [comment]
I can no longer replicate https://github.com/denoland/deno/issues/28908 as the compiled executable on [v2.2.11](https://github.com/denoland/deno/releases/tag/v2.2.11)  outputs nothing. Also, the icon is not applied.


References:

1. https://github.com/denoland/deno/issues/23266#event-17311196438
2. https://github.com/denoland/deno/pull/28934
3. https://github.com/denoland/deno/issues/26400#event-17174319244

**Comment by gowoonhae** [comment]
In my environment, when I do deno compile after deno upgrade rc, the problem still occurs.

**Comment by bartlomieju** [comment]
We have released Deno v2.3.0-rc.1 that should fix this problem. Please upgrade with `deno upgrade rc` and let us know if that fixes your problem. Once confirmed we will prepare a v2.2.12 patch release.

**Comment by dsherret** [comment]
The revert did not fix the issue.

**Comment by dsherret** [comment]
I think I have a fix here: https://github.com/denoland/deno/pull/29005

Sorry this has taken so long, but it was really hard to track down. We will do another rc release for this and then a patch release after as soon as we can.

**Comment by dsherret** [comment]
Still happening in rc2. It seems whatever bug it is sometimes happens and sometimes doesn't

**Comment by dsherret** [comment]
Just an update on this issue:

1. It is most certainly caused by the resource being incorrectly written to the compiled executable.
1. The issue can be resolved by opening the executable in Resource Hacker and saving it. The diff between the two shows several issues.
1. We're going to release a temporary fix in https://github.com/denoland/deno/pull/29024 that falls back to reading the resource data directly from the executable file when reading via winapi fails.

**Comment by dsherret** [comment]
This is fixed in Deno 2.2.12 by using a temporary fallback when loading the resource fails.

```
> deno compile main.ts
Check file:///V:/scratch/main.ts
Compile file:///V:/scratch/main.ts to scratch.exe

Embedded Files

scratch.exe
└── main.ts (19B)

Files: 1.24KB
Metadata: 1.15KB
Remote modules: 12B

> ./scratch.exe
HI
```
