### ISSUE TITLE
Deno.createHttpClient: setting poolIdleTimeout to a number spins the event loop

### ISSUE THREAD

**Issue by lrowe** [denoland/deno#29444]
Version: Deno 2.3.3

I was attempting to disable connection pooling by setting `poolIdleTimeout: 0` (the correct way seems to be setting `poolMaxIdlePerHost: 0`) and noticed that setting `poolIdleTimeout` to any number ends up spinning the event loop at that number of milliseconds which you can observe with strace.

Run a server from another terminal:

    deno run --allow-net 'data:,Deno.serve(() => new Response("hello"))'

Then fetch with that client under strace:

    strace deno run --allow-net 'data:,const client = Deno.createHttpClient({ poolIdleTimeout: 100 }); const res = await fetch("http:127.0.0.1:8000/", { client }); await res.bytes(); await new Promise(resolve=>setTimeout(resolve, 5000));'

```
...
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 28
fcntl(28, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(28, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
connect(28, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(5, EPOLL_CTL_ADD, 28, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=3363637376, u64=108575841912960}}) = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}, {events=EPOLLOUT, data={u32=3363637376, u64=108575841912960}}], 1024, 8165) = 2
getsockopt(28, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
setsockopt(28, SOL_TCP, TCP_NODELAY, [0], 4) = 0
getpeername(28, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("127.0.0.1")}, [128 => 16]) = 0
getsockname(28, {sa_family=AF_INET, sin_port=htons(35462), sin_addr=inet_addr("127.0.0.1")}, [128 => 16]) = 0
sendto(28, "GET / HTTP/1.1\r\naccept: */*\r\nacc"..., 123, MSG_NOSIGNAL, NULL, 0) = 123
epoll_wait(3, [{events=EPOLLIN|EPOLLOUT, data={u32=3363637376, u64=108575841912960}}], 1024, 8165) = 1
recvfrom(28, "HTTP/1.1 200 OK\r\ncontent-type: t"..., 8192, 0, NULL, NULL) = 143
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
mmap(0x2ee19aac0000, 520192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2ee19aac0000
madvise(0x2ee19aac0000, 520192, MADV_DONTFORK) = 0
munmap(0x2ee19ab00000, 258048)          = 0
mmap(0x394fcadc0000, 520192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x394fcadc0000
madvise(0x394fcadc0000, 520192, MADV_DONTFORK) = 0
munmap(0x394fcae00000, 258048)          = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 1) = 1
epoll_wait(3, [], 1024, 1)              = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 98) = 1
epoll_wait(3, [], 1024, 98)             = 0
epoll_wait(3, [], 1024, 1)              = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
shutdown(28, SHUT_WR)                   = 0
epoll_ctl(5, EPOLL_CTL_DEL, 28, NULL)   = 0
close(28)                               = 0

# connection closed after poolIdleTimeout but epoll continues spinning

epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 62) = 1
epoll_wait(3, [], 1024, 61)             = 0
epoll_wait(3, [], 1024, 37)             = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8

epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 90) = 1
epoll_wait(3, [], 1024, 90)             = 0
epoll_wait(3, [], 1024, 8)              = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8

epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 54) = 1
epoll_wait(3, [], 1024, 54)             = 0
epoll_wait(3, [], 1024, 45)             = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8

... repeats until the promise timeout.
```

We also see that setting `poolIdleTimeout: true` has the same effect as setting `poolIdelTimeout: false` despite leading to different branches in the rust side

https://github.com/denoland/deno/blob/bc8b191b7c8df03dab8ee084506df87a32143281/ext/fetch/lib.rs#L1038-L1047

    strace deno run --allow-net 'data:,const client = Deno.createHttpClient({ poolIdleTimeout: true }); const res = await fetch("http:127.0.0.1:8000/", { client }); await res.bytes(); await new Promise(resolve=>setTimeout(resolve, 1000));'

```
...
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 28
fcntl(28, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(28, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
connect(28, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(5, EPOLL_CTL_ADD, 28, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=1498466432, u64=110906143983744}}) = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}, {events=EPOLLOUT, data={u32=1498466432, u64=110906143983744}}], 1024, 8166) = 2
getsockopt(28, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
setsockopt(28, SOL_TCP, TCP_NODELAY, [0], 4) = 0
getpeername(28, {sa_family=AF_INET, sin_port=htons(8000), sin_addr=inet_addr("127.0.0.1")}, [128 => 16]) = 0
getsockname(28, {sa_family=AF_INET, sin_port=htons(58750), sin_addr=inet_addr("127.0.0.1")}, [128 => 16]) = 0
sendto(28, "GET / HTTP/1.1\r\naccept: */*\r\nacc"..., 123, MSG_NOSIGNAL, NULL, 0) = 123
epoll_wait(3, [{events=EPOLLIN|EPOLLOUT, data={u32=1498466432, u64=110906143983744}}], 1024, 8166) = 1
recvfrom(28, "HTTP/1.1 200 OK\r\ncontent-type: t"..., 8192, 0, NULL, NULL) = 143
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
mmap(0x1e0326dc0000, 520192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x1e0326dc0000
madvise(0x1e0326dc0000, 520192, MADV_DONTFORK) = 0
munmap(0x1e0326e00000, 258048)          = 0
mmap(0x2ddb11300000, 520192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2ddb11300000
madvise(0x2ddb11300000, 520192, MADV_DONTFORK) = 0
munmap(0x2ddb11340000, 258048)          = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 0) = 1
epoll_wait(3, 

# event loop blocks here until promise timeout

[], 1024, 997)            = 0
epoll_wait(3, [], 1024, 3)              = 0
futex(0x77ccc4901240, FUTEX_WAKE_PRIVATE, 1) = 1
...

# but connection is not closed until just before exit

shutdown(28, SHUT_WR)                   = 0
epoll_ctl(5, EPOLL_CTL_DEL, 28, NULL)   = 0
close(28)                               = 0
write(4, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_wait(3, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, 7157) = 1
futex(0x77ccb85f7548, FUTEX_WAKE_PRIVATE, 1) = 1
close(3)                                = 0
close(8)                                = 0
close(5)                                = 0
close(4)                                = 0
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x77ccc4910000, 12288)           = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by bartlomieju** [comment]
I tried to reproduce this on Deno 2.8.2 and the runaway event-loop spin doesn't seem to happen anymore.

I couldn't run `strace` (tested on macOS, not Linux), so I probed it indirectly: a 1ms `poolIdleTimeout` over a 5s idle should produce roughly 5000 wakeups if the reaper kept spinning after the connection is reaped, but instructions retired grew only ~2% over the `poolIdleTimeout: false` baseline, and the process was otherwise idle. That's the opposite of the original strace, where epoll kept waking every N ms even after the connection was closed.

My guess is this was fixed by the `hyper-util` upgrade (current is 0.1.17, much newer than what 2.3.3 shipped) — hyper-util reworked the pool idle interval so the reaper stops when the pool has no connections, which matches the reported symptom exactly.

Could you confirm whether you still see the spin on a current version (2.8.x) under `strace` on Linux? If it's gone we can close this.

Separately, the `poolIdleTimeout: true` vs `false` observation is a real but cosmetic point: in the Rust code `true` falls through to hyper's default (90s) while `false` means never expire, so they take different branches but look identical in a short test because neither reaps the connection during the test window.

**Comment by lrowe** [comment]
I can still reproduce this with Deno 2.8.3.

Will see if I can find some time to dig further. Putting a gdb breakpoint in `spawn_idle_interval` might be a good place to start.

https://github.com/hyperium/hyper-util/blob/3021828e4af74f130c0ad2ddadd30fba171717e7/src/client/legacy/pool.rs#L419

**Comment by lrowe** [comment]
Seems we can use the rust level tracing functionality to see what's going on even with the released build of deno:

```
$ DENO_LOG=hyper_util::client=trace deno run --allow-net 'data:,const client = Deno.createHttpClient({ pool
IdleTimeout: 100 }); const res = await fetch("http:127.0.0.1:8000/", { client }); await res.bytes(); await new Promise(resolve=>setT
imeout(resolve, 5000));'
TRACE RS - hyper_util::client::legacy::pool:679 - checkout waiting for idle connection: ("http", 127.0.0.1:8000)
TRACE RS - hyper_util::client::legacy::connect::http:482 - Http::connect; scheme=Some("http"), host=Some("127.0.0.1"), port=Some(Port(8000))
DEBUG RS - hyper_util::client::legacy::connect::http:768 - connecting to 127.0.0.1:8000
DEBUG RS - hyper_util::client::legacy::connect::http:771 - connected to 127.0.0.1:8000
TRACE RS - hyper_util::client::legacy::client:575 - http1 handshake complete, spawning background dispatcher task
TRACE RS - hyper_util::client::legacy::client:600 - waiting for connection to be ready
TRACE RS - hyper_util::client::legacy::client:610 - connection is ready
TRACE RS - hyper_util::client::legacy::pool:721 - checkout dropped for ("http", 127.0.0.1:8000)
TRACE RS - hyper_util::client::legacy::pool:348 - put; add idle connection for ("http", 127.0.0.1:8000)
DEBUG RS - hyper_util::client::legacy::pool:395 - pooling idle connection for ("http", 127.0.0.1:8000)
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:492 - idle interval evicting expired for ("http", 127.0.0.1:8000)
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:799 - idle interval checking for expired
TRACE RS - hyper_util::client::legacy::pool:810 - pool closed, canceling idle interval
```

The IdleTask is spawned in the pools first connection and that loops every poolIdleTimeout until the pool itself is closed.: https://github.com/hyperium/hyper-util/blob/3021828e4af74f130c0ad2ddadd30fba171717e7/src/client/legacy/pool.rs#L784-L812

Seems that stopping the IdleTask when the pool is empty is a fairly small change. Will see if hyper-util is open to it. https://github.com/lrowe/hyper-util/commit/e82b31fc232407bf03a5c0abc3a20be109cd7ed4
