### ISSUE TITLE
Update building from source guide for Windows

### ISSUE THREAD

**Issue by stefnotch** [denoland/deno#29820]
With https://github.com/denoland/deno/pull/28244 merged, Deno is now using the widely used aws-lc-rs.
aws-lc-rs is not pure Rust code and instead depends on being able to build C/C++ code and assembly code.

This means that the ["building from source" section](https://github.com/denoland/deno/blob/main/.github/CONTRIBUTING.md#building-from-source) of the contributing guide for Deno needs to be updated 

Notably, [on Windows the aws-lc-rs dependency requires](https://aws.github.io/aws-lc-rs/requirements/windows.html)
- A C/C++ compiler. I believe that [this section](https://github.com/denoland/deno/blob/main/.github/CONTRIBUTING.md#windows) covers that. I wonder if that section actually asks for too many dependencies.
- CMake. The CMake that ships with Visual Studio *cannot* be used for working on Deno, since it is not a globally available tool. It is only available from within a "Developer Command Prompt" and is entirely invisible to rust-analyzer.
  - Thus, one has to go out of their way to install CMake like aws-lc-rs recommends.
- The NASM assembler. This can be avoided if Deno either sets the `prebuilt-nasm` feature flag, or if the user sets the `AWS_LC_SYS_PREBUILT_NASM` environment variable. The latter requires me to do it globally for the entire system, otherwise it's easy for tools like rust-analyzer to not pick up on it.

Finally, the"building from source" guide mentions requiring a protobuf compiler. I believe that that is outdated information. I do not see what protobuf would be used for.

**Comment by paulhey** [comment]
I ran into an issue building deno from crates.io using CMake 4 on Windows. Chocolatey and Scoop both default to CMake 4 and I encountered this [issue](https://github.com/aws/aws-lc-rs/issues/755). It would appear that deno currently has `aws-lc-sys@0.26.0` and the issue linked resolves it in `aws-lc-sys@0.28.0`. My work around was to force Scoop to install the latest CMake 3 (`scoop install cmake@3.31.8`)

**Comment by lucasfernog-crabnebula** [comment]
> I ran into an issue building deno from crates.io using CMake 4 on Windows. Chocolatey and Scoop both default to CMake 4 and I encountered this [issue](https://github.com/aws/aws-lc-rs/issues/755). It would appear that deno currently has `aws-lc-sys@0.26.0` and the issue linked resolves it in `aws-lc-sys@0.28.0`. My work around was to force Scoop to install the latest CMake 3 (`scoop install cmake@3.31.8`)

I faced the same issue, can we update to 0.28? or is there a compatibility problem?

**Comment by ryuapp** [comment]
> I faced the same issue, can we update to 0.28? or is there a compatibility problem?

This seems to have been resolved with the following PR:

- https://github.com/denoland/deno/pull/31307

At least it works fine on my Windows.

**Comment by stefnotch** [comment]
aws-lc-rs's latest version should no longer require cmake on Windows! https://github.com/aws/aws-lc-rs/issues/828

So what's left to do is
- Updating the dependency in Deno
- Testing the installation experience on a reasonably freshly installed Windows machine

**Comment by stefnotch** [comment]
I tested it out just now, with manually updated dependencies. Yes, aws-lc-rs and libuv-sys-lite work as intended :)

Though, one has to set the environment variable `AWS_LC_SYS_PREBUILT_NASM` to `1`. Otherwise aws-lc-rs will require the NASM assembler and will refuse to compile.

And the [libz-sys dependency](https://github.com/rust-lang/libz-sys?tab=readme-ov-file#zlib-ng) is still a problem child. It wants cmake.
For that one, there are 3 options
- Use the not officially supported flag https://github.com/denoland/deno/pull/27762/changes/113896f710310c0d35064d7e22b4da7178c65911
- Install cmake, which is painful to get to work
- Use a Rusty dependency, such as https://github.com/trifectatechfoundation/zlib-rs . This is almost a drop-in replacement.

And a new problem child has joined the dependency tree. It is none other than https://github.com/rusqlite/rusqlite .
While Deno does set the `"bundled"` feature, Deno also sets the [`"session"` feature, which enables `"buildtime_bindgen"`](https://github.com/rusqlite/rusqlite/blob/890be7bab5a8cef767b2c373ae14b19959c4f3de/libsqlite3-sys/Cargo.toml#L42-L43) and ends up requiring more native libraries 
And for that one, I don't have any suggestions. Other than the very cop-out answer of "use Linux to work on Deno, clearly that's the blessed path".
