### ISSUE TITLE
Deno.run with large amounts of newlines in piped stdout gets stuck

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#4568]
### Reproduction
1. Generate test file:
```bash
echo "hello world" > file.txt
for i in {1..10}; do cat file.txt file.txt > file2.txt && mv file2.txt file.txt; done
```
2. create test.js
```js
const proc = Deno.run({
  cmd: ["cat", "test.json"],
  stdout: "piped",
  stderr: "piped"
});

const status = await proc.status();
```
3. run test.ts
```bash
deno --allow-run test.js
```

4. Deno gets stuck on `await proc.status()`.

**Comment by ry** [comment]
I can't repeat it.

**Comment by lucacasonato** [comment]
Managed to narrow it down to only happening when the file that is being opened is stored on an NTFS drive - this is really weird. It's not happening on macOS for me either, just on Linux + file.txt on NTFS drive. If the file.txt is on ext4 its fine. I'll try on Windows and report back. This might be a weird NTFS driver bug on Linux though - had some of those before.

**Comment by lucacasonato** [comment]
Checked on windows - not happening there. I'll close this and reopen if I have any more exact information about what is going on.

**Comment by lucacasonato** [comment]
Ok I have a reliable reproduction, on macOS now:

1. Save this file as `lib.deno.d.ts`: https://gist.github.com/lucacasonato/9a81ef88fa7f43ba8fc1297a04187ac9

2. Create `test.js`: 
```js
const proc = Deno.run({
  cmd: ["deno", "doc", "lib.deno.d.ts", "--json", "--reload"],
  stdout: "piped",
  stderr: "piped"
});

const status = await proc.status();
```
3. Run `deno --allow-run test.js`

4. Deno gets stuck on `await proc.status()`.

**Comment by bartlomieju** [comment]
@lucacasonato does error happen if you `await proc.output()` and `await proc.stderrOutput()` before awaiting on status? It seems that `unit_test_runner` produces similar sized output and works without a problem.

**Comment by lucacasonato** [comment]
Everything works as expected when I add `await proc.output()` between the run call and the `proc.status()`call. `await proc.stderrOutput()` has no effect.

**Comment by youurayy** [comment]
This happens when the stdout is bigger than (?) 64KiB, consider:
```js
const p = Deno.run({

  // this will work in any case:
  // cmd: [ 'curl', '-s', 'https://deno.land' ], // 4KB

  // this will work only if stdout is drained below:
  cmd: [ 'curl', '-s', 'https://en.wikipedia.org/wiki/Deno_(software)' ], // 79KB

  stdout: 'piped',
  stderr: 'piped'
})

console.log('here 1')

// await p.output() // drain the stdout here
console.log('here 1.1')

await p.stderrOutput()
console.log('here 1.2')

const { code } = await p.status()
console.log('here 2, code: ' + code)

```

You have to uncomment the `// drain the stdout here` line to make the Wikipedia link work.
Tested on Windows.
Run with `deno run --allow-run test.js`.

**Comment by lucacasonato** [comment]
I just ran into this again on the registry. It is a very annoying bug because it is so not logical. I think many people have and will run into it. I also ran into it for doc.deno.land. We should really address this one soon.

**Comment by exside** [comment]
@lucacasonato I think I did run into some form of it: https://github.com/denoland/deno/issues/7208#issuecomment-687523182 but can't explain it...

**Comment by ebebbington** [comment]
@lucacasonato I get the same issue when the sub process is asking for stdin (different to what i mentioned before), it just hangs on the `await p.status()`, not sure in this scenario if it's possible to address or even a bug

**Comment by rok-star** [comment]
encountered same issue again! here is my work around:
```typescript
const proc = Deno.run({ cmd, stderr: 'piped', stdout: 'piped' });
const [ stderr, stdout, status ] = await Promise.all([ proc.stderrOutput(), proc.output(), proc.status() ]);
```

**Comment by Soremwar** [comment]
Stll happening on latest canary

**Comment by bartlomieju** [comment]
So after further investigation I think this works as it should. 

`stdout` and `stderr` pipes should be closed manually before awaiting on the status, so @rok-star's solution is the preferable one for the time being. I will update the docs for the `Deno.run` API accordingly, but overall the API is not very user-friendly and I think it might have to undergo a rework for 2.0 to make it more like [Tokio's `Child` API](https://docs.rs/tokio/1.1.1/tokio/process/struct.Child.html) (I will open a separate issue for it).

> @lucacasonato I get the same issue when the sub process is asking for stdin (similar to what i mentioned before), it just hangs on the `await p.status()`, not sure in this scenario if it's possible to address or even a bug

@ebebbington this should no longer be the case, calling `p.status()` will close `stdin` of the child process before awaiting on the status to avoid the deadlock (https://docs.rs/tokio/1.1.1/tokio/process/struct.Child.html#method.wait).

**Comment by ebebbington** [comment]
@bartlomieju ok cool thanks, I’ll just mention that this issue doesn’t affect me anymore I guess as I moved to another solution but good to hear it is addressed

**Comment by dgreensp** [comment]
This was very surprising to encounter, and I don't know what I would have done if I hadn't found this issue!

FWIW the examples of Deno.run that I was working off of (incorrectly) read `status` before `output`, e.g. in the manual: https://deno.land/manual/examples/subprocess I wouldn't have thought to specifically read the docs for the Process type.

**Comment by aapoalas** [comment]
Is this still happening, or has the deadlock been fixed?

**Comment by tiesselune** [comment]
This is still happening (just ran into it using `Deno.run`, but [the documentation does warn the user](https://deno.land/api@v1.34.1?s=Deno.Process&p=prototype.status) that `stdout` and `stderr` must be closed when piped so the process can exit. (So `output` must be read, basically, before calling `status`)

The surprising part is that it does not happen on "small" outputs, only on big ones, which is a bit destabilizing (and can result in seemingly arbitrary hangs when other commands succeed), reason for which I stumbled on this thread in the first place...

**Comment by crowlKats** [comment]
This doesn't happen with the new subprocess API (`Deno.Command`), so closing since `Deno.run` is deprecated.
